import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { AuthState } from "./auth.types";

// Define the initial state for the authentication slice
const initialState: AuthState = {
    isLoggedIn: false,
    userRole: null,
  };
  
  // Create the authentication slice
  const authSlice = createSlice({
    name: 'auth',
    initialState,
    reducers: {
      login(state, action: PayloadAction<string>) {
        state.isLoggedIn = true;
        state.userRole = action.payload; // Podría ser "admin" o "user" dependiendo del usuario
      },
      logout(state) {
        state.isLoggedIn = false;
        state.userRole = null;
      },
    },
});

// Extract the action creators from the auth slice
export const { login, logout } = authSlice.actions;

// Selectors to extract specific data from the authentication slice
export const selectLoggedIn = (state: { auth: AuthState }) => state.auth.isLoggedIn;
export const selectUserRole = (state: { auth: AuthState }) => state.auth.userRole;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
